name: Test it builds on push or PR.

on:
  push:
    paths-ignore:
      - '*.md'
      - '.github/**'
      - 'extras/**'
      - 'src/main/resources/**'

  pull_request:
      paths-ignore:
        - '*.md'
        - '.github/**'
        - 'extras/**'
        - 'src/main/resources/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup JDK 16
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '16'

      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup Build
        run: chmod +x gradlew
        
      - name: Build with Gradle
        id: build
        run: ./gradlew build

      - name: Check the license header exists (Run ./gradlew updateLicenses if it errors)
        id: licenseCheck
        run: ./gradlew licenseCheck
